DESTDIR = ../../

SRC = adapter.cpp book_make.cpp epd.cpp io.cpp move.cpp option.cpp	\
      posix.cpp square.cpp attack.cpp book_merge.cpp fen.cpp line.cpp	\
      move_do.cpp parse.cpp random.cpp uci.cpp board.cpp colour.cpp	\
      game.cpp list.cpp move_gen.cpp pgn.cpp san.cpp util.cpp		\
      book.cpp engine.cpp hash.cpp main.cpp move_legal.cpp piece.cpp	\
      search.cpp


