DESTDIR = /usr/local

SRC = attack.cpp hash.cpp move_check.cpp option.cpp pst.cpp	\
      search_full.cpp util.cpp board.cpp list.cpp move_do.cpp	\
      pawn.cpp pv.cpp see.cpp value.cpp book.cpp main.cpp	\
      move_evasion.cpp piece.cpp random.cpp sort.cpp vector.cpp	\
      eval.cpp material.cpp move_gen.cpp posix.cpp recog.cpp	\
      square.cpp fen.cpp move.cpp move_legal.cpp protocol.cpp	\
      search.cpp trans.cpp

